  # Influx DB configuration
influxdb:
  server:
    - ip: 172.30.232.250
      port: 8086
      db: trapEvent
      user: sabaszx 
      pass: admin
# all measurement
measurement: client_each_floor
tags:
    floor_number:number
fields:
    item:count

measurement: user
tags:
    type:
        - associate
        - disassociate
fields:
    item:count

