# All traps processing configuration
all:
  measurement: Event
  fields:
    - UptimeInstance
# Special processing based on Event ??
mappings:
  ClientSessionTrap:
    measurement: Event
    tags:
      - ApName
      - SSID
    fields:
      - ClientIpAddress
      - ClientUsername
  ClientMovedToRunState:
    measurement: Event
    tags:
      - ApName
      - SSID
    fields:
      - ClientIpAddress
      - ClientUsername 